apiVersion: v1
kind: Service
metadata:
  name: new-app-service
  namespace: production
spec:
  selector:
    app: new-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
